#!/usr/sbin/nft -f

flush ruleset

table ip filter {
    chain input {
        type filter hook input priority filter; policy drop;

        iif lo accept
        ct state established,related accept

	meta skgid qbittorrent accept
	tcp dport 33112 drop
	udp dport 33112 drop

        ip protocol icmp icmp type { destination-unreachable, time-exceeded, parameter-problem } accept

        log prefix "DROP INPUT: " counter
    }

    chain output {
        type filter hook output priority filter; policy drop;

        oif lo accept
        ct state established,related accept

	meta skgid qbittorrent accept
        udp dport 1900 ip daddr 239.255.255.250 drop

        tcp dport { 80, 443 } meta skuid privoxy accept
	ip daddr { 1.1.1.1, 1.0.0.1 } tcp dport 853 meta skuid unbound accept

        log prefix "REJECT OUTPUT: " counter
        reject
    }

    chain forward {
        type filter hook forward priority filter; policy drop;
    }
}
        #meta skgid qbittorrent reject
        #udp sport 33112
