preload = /home/nowa/Lilith.png
preload = /home/nowa/Downloads/Background_016_001.png
preload = /home/nowa/Downloads/Background_017_002.png

wallpaper = ,/home/nowa/Lilith.png
wallpaper = ,/home/nowa/Downloads/Background_016_001.png
#wallpaper = ,/home/nowa/Downloads/Background_017_002.png
